@startuml Diagrama de classe

class Livro {
  - titulo : String
  - autor : String
  - resumo : String
  - qntDisponivel : int
  + emprestar()
  + devolver()
}

class Usuario {
    - nome : String
    - idade : int 
    + meusLivros()
    + devolverLivro(livro: Livro)
}

class Bibliotecario {
    + solicitacoesEmprestimo();
    + emprestar(livro: Livro)
}

class Emprestimo {
    - dataEmpretimo
    - dataDevolucao
    + calcularAtraso()
}

Usuario --|> Emprestimo
Emprestimo --|> Livro
Bibliotecario --|> Livro

@enduml