@startuml
skinparam actorStyle awesome
left to right direction



actor "Leitor"
actor "Admin"


rectangle "Sistema Almanaque" {


  package "Autenticação" {
    usecase "Criar Conta" as UC_Create
    usecase "Fazer Login" as UC_Login
    usecase "Sair do Sistema" as UC_Exit
  }


  package "Funções Comuns" {
    usecase "Pesquisar Livros" as UC_Search
    usecase "Fazer Logout" as UC_Logout
  }


  package "Funções do Leitor" {
    usecase "Mostrar Livros Recomendados" as UC_Recomend <<stub>>
    usecase "Consultar Multas" as UC_LeitorMulta <<stub>>
    usecase "Devolver Livro" as UC_Devolve <<stub>>
  }


  package "Funções do Admin" {
    usecase "Mostrar Todos os Livros" as UC_ListAll
    usecase "Cadastrar Livro" as UC_AddLivro
    usecase "Consultar Multas (Admin)" as UC_AdminMulta <<stub>>
    usecase "Realizar Empréstimo" as UC_Emprestimo <<stub>>
  }
}


Guest -- UC_Create
Guest -- UC_Login
Guest -- UC_Exit


User -- UC_Search
User -- UC_Logout


Leitor -- UC_Recomend
Leitor -- UC_LeitorMulta
Leitor -- UC_Devolve


Admin -- UC_ListAll
Admin -- UC_AddLivro
Admin -- UC_AdminMulta
Admin -- UC_Emprestimo

@enduml